reworked custom script mechanism

diff --git a/base_installer/base_install_scripts.d/1500-run-custom-install-script-env1 b/base_installer/base_install_scripts.d/1500-run-custom-install-script-env1
--- a/base_installer/base_install_scripts.d/1500-run-custom-install-script-env1
+++ b/base_installer/base_install_scripts.d/1500-run-custom-install-script-env1
@@ -4,21 +4,22 @@
 
 # Note that since ENV1 will be cloned to ENV2 and ENV3, ENV1-custom-install.sh is actually more of an ENVALL than an ENV1 custom script
 
-if ! [ -f ../custom/ENV1-custom-install.sh ] ; then
-	echo "No custom file found, using template from template directory."
+if ! [ -x ../custom/ENV1-custom-install.sh ] ; then
+	echo "No executable custom file found, using template from template directory."
 	cp ../templates/ENV1-custom-install.sh ../custom/
+	chmod +x ../custom/ENV1-custom-install.sh
+	ENV1_NO_CUSTOM=true
 fi
 if bash -n ../custom/ENV1-custom-install.sh ; then
 	echo "A syntactically correct custom install file for ENV1 has been detected. Executing in changeroot ..."
 	rsync -aPvH ../custom/ENV1-custom-install.sh $MOUNTPOINT/ENV1-custom-install.sh && \
-	chmod +x $MOUNTPOINT/ENV1-custom-install.sh
 	chroot $MOUNTPOINT ./ENV1-custom-install.sh && \
 	chmod -x $MOUNTPOINT/ENV1-custom-install.sh
 elif ! bash -n ../custom/ENV1-custom-install.sh ; then
-	echo "Syntax error in ./ENV1-custom-install.sh detected. Skipping, but continuing ..."
+	echo "Syntax error in ENV1-custom-install.sh detected. Skipping, but continuing ..."
 	mv $MOUNTPOINT/ENV1-custom-install.sh $MOUNTPOINT/ENV1-custom-install.broken
-	exit 0
-else
-	echo "No custom install file for ENV1 found, continuing ..."
-	exit 0
 fi
+if [ -n "$ENV1_NO_CUSTOM" ]; then
+	rm ../custom/ENV1-custom-install.sh
+fi
+exit 0
diff --git a/base_installer/base_install_scripts.d/2400-run-custom-install-script-env2 b/base_installer/base_install_scripts.d/2400-run-custom-install-script-env2
--- a/base_installer/base_install_scripts.d/2400-run-custom-install-script-env2
+++ b/base_installer/base_install_scripts.d/2400-run-custom-install-script-env2
@@ -2,21 +2,22 @@
 
 # check for custom install script; execute it if present, and remove the executable bit afterwards (so it runs only once)
 
-if ! [ -f ../custom/ENV2-custom-install.sh ] ; then
-	echo "No custom file found, using template from template directory."
+if ! [ -x ../custom/ENV2-custom-install.sh ] ; then
+	echo "No executable custom file found, using template from template directory."
 	cp ../templates/ENV2-custom-install.sh ../custom/
+	chmod +x ../custom/ENV2-custom-install.sh
+	ENV2_NO_CUSTOM=true
 fi
 if bash -n ../custom/ENV2-custom-install.sh ; then
 	echo "A syntactically correct custom install file for ENV2 has been detected. Executing in changeroot ..."
 	rsync -aPvH ../custom/ENV2-custom-install.sh $MOUNTPOINT/ENV2-custom-install.sh && \
-	chmod +x $MOUNTPOINT/ENV2-custom-install.sh
 	chroot $MOUNTPOINT ./ENV2-custom-install.sh && \
 	chmod -x $MOUNTPOINT/ENV2-custom-install.sh
 elif ! bash -n ../custom/ENV2-custom-install.sh ; then
-	echo "Syntax error in ./ENV2-custom-install.sh detected. Skipping, but continuing ..."
+	echo "Syntax error in ENV2-custom-install.sh detected. Skipping, but continuing ..."
 	mv $MOUNTPOINT/ENV2-custom-install.sh $MOUNTPOINT/ENV2-custom-install.broken
-	exit 0
-else
-	echo "No custom install file for ENV2 found, continuing ..."
-	exit 0
 fi
+if [ -n "$ENV2_NO_CUSTOM" ]; then
+	rm ../custom/ENV2-custom-install.sh
+fi
+exit 0
diff --git a/base_installer/base_install_scripts.d/2900-run-custom-install-script-env3 b/base_installer/base_install_scripts.d/2900-run-custom-install-script-env3
--- a/base_installer/base_install_scripts.d/2900-run-custom-install-script-env3
+++ b/base_installer/base_install_scripts.d/2900-run-custom-install-script-env3
@@ -2,21 +2,22 @@
 
 # check for custom install script; execute it if present, and remove the executable bit afterwards (so it runs only once)
 
-if ! [ -f ../custom/ENV3-custom-install.sh ] ; then
-	echo "No custom file found, using template from template directory."
+if ! [ -x ../custom/ENV3-custom-install.sh ] ; then
+	echo "No executable custom file found, using template from template directory."
 	cp ../templates/ENV3-custom-install.sh ../custom/
+	chmod +x ../custom/ENV3-custom-install.sh
+	ENV3_NO_CUSTOM=true
 fi
 if bash -n ../custom/ENV3-custom-install.sh ; then
 	echo "A syntactically correct custom install file for ENV3 has been detected. Executing in changeroot ..."
 	rsync -aPvH ../custom/ENV3-custom-install.sh $MOUNTPOINT/ENV3-custom-install.sh && \
-	chmod +x $MOUNTPOINT/ENV3-custom-install.sh
 	chroot $MOUNTPOINT ./ENV3-custom-install.sh && \
 	chmod -x $MOUNTPOINT/ENV3-custom-install.sh
 elif ! bash -n ../custom/ENV3-custom-install.sh ; then
-	echo "Syntax error in ./ENV3-custom-install.sh detected. Skipping, but continuing ..."
+	echo "Syntax error in ENV3-custom-install.sh detected. Skipping, but continuing ..."
 	mv $MOUNTPOINT/ENV3-custom-install.sh $MOUNTPOINT/ENV3-custom-install.broken
-	exit 0
-else
-	echo "No custom install file for ENV3 found, continuing ..."
-	exit 0
 fi
+if [ -n "$ENV3_NO_CUSTOM" ]; then
+	rm ../custom/ENV3-custom-install.sh
+fi
+exit 0
