increased chattiness

diff --git a/base_installer/base_install_scripts.d/2600-clone-env1root-to-env3root b/base_installer/base_install_scripts.d/2600-clone-env1root-to-env3root
--- a/base_installer/base_install_scripts.d/2600-clone-env1root-to-env3root
+++ b/base_installer/base_install_scripts.d/2600-clone-env1root-to-env3root
@@ -1,11 +1,18 @@
 #!/bin/bash -e
 
 # now we are cloning ENV1 rootfs to ENV3 rootfs
+echo "Cloning ENV1's rootfs to ENV3's rootfs ..."
 while ! dd if=$PARTFIVE of=$PARTSEVEN bs=4096k status=progress; do sleep 1; done
 
 # check if write to block device really succeeded
-test -b $PARTSEVEN || (echo "Device $PARTSEVEN is no longer a block device!" ; exit 1)
+if [ -b $PARTSEVEN ]; then
+	echo "Cloning complete."
+else
+	echo "Error: Device $PARTSEVEN is no longer a block device! Aborting."
+	exit 1
+fi
 
+echo "Changing partition label to rootfs2 and assigning new UUID ..."
 # to make sure we can tell our clones apart, we set a new LABEL and UUID
 tune2fs -L rootfs3 -U $(uuid) $PARTSEVEN
 
